title = "Haihaus Trails"
author = "Daniel Hall"
base_url = "https://trails.hai.haus"

default_language = "en"


# Processing
compile_sass = true
build_search_index = true
generate_sitemap = true
generate_robots_txt = true

[search]
index_format = "elasticlunr_json"

[markdown]
external_links_target_blank = true

# can i has fancy?
bottom_footnotes = true
render_emoji = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[extra]
